<?php


namespace modava\tiny;


use modava\tiny\components\FileManagerPermisstion;
use yii\base\Widget;
use yii\helpers\Html;

class FileManager extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $view = $this->getView();

        $insFile = FileManagerAsset::register($view);

        $link = $insFile->baseUrl . '/filemanager/';

        $configPath = [
            'upload_dir' => '/img/',
            'current_path' => '../../../../../../frontend/web/img/',
            'thumbs_base_path' => '../../../../../../frontend/web/thumbs/',
            'base_url' => \Yii::getAlias('@frontendUrl'),
            'FileManagerPermisstion' => FileManagerPermisstion::setPermissionFileAccess()
        ];
        $filemanager_access_key = urlencode(serialize($configPath));


        return $this->render('fileWidgets', [
            'link' => $link,
            'filemanager_access_key' => $filemanager_access_key
        ]);
    }
}